/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author SHINDY OEMARDY
 */
public class PilihGambarButtonFullScreen extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarButton
     */
    public PilihGambarButtonFullScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        buttonpanel = new javax.swing.JPanel();
        ichikabtn = new javax.swing.JButton();
        itsukibtn = new javax.swing.JButton();
        mikubtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        imagepanel = new javax.swing.JPanel();
        ichika = new javax.swing.JLabel();
        itsuki = new javax.swing.JLabel();
        miku = new javax.swing.JLabel();
        nino = new javax.swing.JLabel();
        yotsuba = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonpanel.setBackground(new java.awt.Color(102, 255, 102));

        ichikabtn.setText("ichika");
        ichikabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ichikabtnActionPerformed(evt);
            }
        });
        buttonpanel.add(ichikabtn);

        itsukibtn.setText("itsuki");
        itsukibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itsukibtnActionPerformed(evt);
            }
        });
        buttonpanel.add(itsukibtn);

        mikubtn.setText("miku");
        mikubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mikubtnActionPerformed(evt);
            }
        });
        buttonpanel.add(mikubtn);

        jButton1.setText("nino");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        buttonpanel.add(jButton1);

        jButton3.setText("yotsuba");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        buttonpanel.add(jButton3);

        exitbtn.setText("exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        buttonpanel.add(exitbtn);

        getContentPane().add(buttonpanel, java.awt.BorderLayout.PAGE_START);

        imagepanel.setBackground(new java.awt.Color(255, 153, 153));
        imagepanel.setLayout(new java.awt.CardLayout());

        ichika.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ichika.png"))); // NOI18N
        imagepanel.add(ichika, "0");

        itsuki.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/itsuki.jpg"))); // NOI18N
        imagepanel.add(itsuki, "1");

        miku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/miku.jpg"))); // NOI18N
        imagepanel.add(miku, "2");

        nino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/nino.jpg"))); // NOI18N
        imagepanel.add(nino, "3");

        yotsuba.setBackground(new java.awt.Color(153, 255, 153));
        yotsuba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/yotsuba.jpg"))); // NOI18N
        imagepanel.add(yotsuba, "4");

        getContentPane().add(imagepanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitbtnActionPerformed

    private void ichikabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ichikabtnActionPerformed
        CardLayout cl =(CardLayout) (imagepanel.getLayout());
        cl.show(imagepanel,"0");
    }//GEN-LAST:event_ichikabtnActionPerformed

    private void itsukibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itsukibtnActionPerformed
      CardLayout cl =(CardLayout) (imagepanel.getLayout());
        cl.show(imagepanel,"1");
    }//GEN-LAST:event_itsukibtnActionPerformed

    private void mikubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mikubtnActionPerformed
      CardLayout cl =(CardLayout) (imagepanel.getLayout());
        cl.show(imagepanel,"2");
    }//GEN-LAST:event_mikubtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    CardLayout cl =(CardLayout) (imagepanel.getLayout());
        cl.show(imagepanel,"3");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      CardLayout cl =(CardLayout) (imagepanel.getLayout());
        cl.show(imagepanel,"4");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PilihGambarButtonFullScreen fullFrame = new PilihGambarButtonFullScreen();
                GraphicsDevice device = 
                        GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
                device.setFullScreenWindow(fullFrame);
                fullFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonpanel;
    private javax.swing.JButton exitbtn;
    private javax.swing.JLabel ichika;
    private javax.swing.JButton ichikabtn;
    private javax.swing.JPanel imagepanel;
    private javax.swing.JLabel itsuki;
    private javax.swing.JButton itsukibtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel miku;
    private javax.swing.JButton mikubtn;
    private javax.swing.JLabel nino;
    private javax.swing.JLabel yotsuba;
    // End of variables declaration//GEN-END:variables
}
