/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;

/**
 *
 * @author SHINDY OEMARDY
 */
public class PilihGambarComboBox extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarButton
     */
    public PilihGambarComboBox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pilihan = new javax.swing.JComboBox<>();
        imagepanel = new javax.swing.JPanel();
        ichika = new javax.swing.JLabel();
        itsuki = new javax.swing.JLabel();
        miku = new javax.swing.JLabel();
        nino = new javax.swing.JLabel();
        yotsuba = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonpanel.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel1.setText("Pilih Gambar");
        buttonpanel.add(jLabel1);

        pilihan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ichika", "itsuki", "miku", "nino", "yotsuba" }));
        pilihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihanActionPerformed(evt);
            }
        });
        buttonpanel.add(pilihan);

        getContentPane().add(buttonpanel, java.awt.BorderLayout.PAGE_START);

        imagepanel.setBackground(new java.awt.Color(102, 102, 255));
        imagepanel.setLayout(new java.awt.CardLayout());

        ichika.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ichika.png"))); // NOI18N
        imagepanel.add(ichika, "0");

        itsuki.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/itsuki.jpg"))); // NOI18N
        imagepanel.add(itsuki, "1");

        miku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/miku.jpg"))); // NOI18N
        imagepanel.add(miku, "2");

        nino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/nino.jpg"))); // NOI18N
        imagepanel.add(nino, "3");

        yotsuba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/yotsuba.jpg"))); // NOI18N
        imagepanel.add(yotsuba, "4");
        yotsuba.getAccessibleContext().setAccessibleName("4");

        getContentPane().add(imagepanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pilihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihanActionPerformed
        CardLayout cl = (CardLayout)(imagepanel.getLayout());
        cl.show(imagepanel,String.valueOf(pilihan.getSelectedIndex()));
    }//GEN-LAST:event_pilihanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihGambarComboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonpanel;
    private javax.swing.JLabel ichika;
    private javax.swing.JPanel imagepanel;
    private javax.swing.JLabel itsuki;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel miku;
    private javax.swing.JLabel nino;
    private javax.swing.JComboBox<String> pilihan;
    private javax.swing.JLabel yotsuba;
    // End of variables declaration//GEN-END:variables
}
